import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ETH Argentina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <li><a href="https://t.me/+2nijw5YHq_hjODkx" target="_blank">Telegram</a></li>
          <li><a href="https://twitter.com/etherargentina?s=11&t=j_w3njfNO2boGMHoQgfS3Q" target="_blank">Twitter</a></li>
        </nav>
      </header>

      <section className="home">
        <h1>ETHEREUM ARGENTINA</h1>
        <h3>El evento de Ethereum más grande de Argentina 🚀</h3>
        <a href="https://t.me/+2nijw5YHq_hjODkx" className="btn">¡Unite a Telegram!</a>
      </section>

      <footer>
        <p>Copyright © 2023 Ethereum Argentina - Todos los derechos reservados.</p>
        <p>Made with ♥️ by Ethereum Argentina team</p>
      </footer>
      <style jsx>{`
        *{
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        html{
          font: normal 16px sans-serif;
          color: #555;
        }

        ul, nav{
          list-style: none;
        }

        a{
          text-decoration: none;
          color: inherit;
          cursor: pointer;

          opacity: 0.9;
        }

        a:hover{
          opacity: 1;
        }

        a.btn{
          color: #fff;
          border-radius: 4px;
          text-transform: uppercase;
          background-color: #2196F3;
          font-weight: 800;
          text-align: center;
        }

        hr{
          width: 150px;
          height: 2px;
          background-color: #2196F3;
          border: 0;
          margin-bottom: 80px;
        }

        section{
          display: flex;
          flex-direction: column;
          align-items: center;

          padding: 125px 100px;
        }

        @media (max-width: 1000px){

          section{
            padding: 100px 50px;
          }

        }

        @media (max-width: 600px){

          section{
            padding: 80px 30px;
          }

        }

        section h3.title{
          color: #414a4f;
          text-transform: capitalize; 
          font: bold 32px;
          margin-bottom: 35px;
          text-align: center;
        }

        section p{
          max-width: 800px;
          text-align: center;
          margin-bottom: 35px;
          padding: 0 20px;
          line-height: 2;
        }

        ul.grid{
          width: 100%;
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
        }


        /*-------------
          Header
        -------------*/

        header{
          position: absolute;
          top: 0;
          left: 0;
          z-index: 10;
          width: 100%;
          display: flex;
          justify-content: space-between;
          align-items: center;
          color: #fff;
          padding: 35px 100px 0;
          background-color: #5989BD;
        }

        header nav{
          display: flex;
        }

        header nav li{
          margin: 0 15px;
          display: inline-block;
          position: relative;
          padding-bottom: 3px;
        }

        header nav li:first-child{
          margin-left: 0;	
        }

        header nav li:last-child{
          margin-right: 0;	
        }

        header nav li::after {
          content: '';
          position: absolute;
          width: 100%;
          transform: scaleX(0);
          height: 1px;
          bottom: 0;
          left: 0;
          background-color: #fff;
          transform-origin: bottom right;
          transition: transform 0.25s ease-out;
        }
        
        header nav li:hover::after {
          transform: scaleX(1);
          transform-origin: bottom left;
        }

        @media (max-width: 1000px){
          header{
            padding: 20px 50px;
          }
        }


        @media (max-width: 700px){
          header{
            flex-direction: column;		
          }

          header h2{
            margin-bottom: 15px;
          }
        }



        /*----------------
          Home Section
        ----------------*/

        .home{
          position: relative;
          justify-content: center;
          min-height: 100vh;
          color: #fff;
          text-align: center;
          background-color: #5989BD;
        }

        .home .background-image{
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background-size: cover;
          background-color: #2196F3;
          z-index: -1;
        }

        .home .background-image:after{
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background-color: #414a4f;
          opacity: 0.75;
        }

        .home h1{
          font: bold 60px 'becker-wood-type';
          margin-bottom: 15px;
          letter-spacing: .2rem;
        }

        .home h3{
          font: normal 28px;
          margin-bottom: 40px;
        }

        .home a.btn{
          padding: 20px 46px;
          background-color: #FFF;
          color: #5989BD;
        }

        @media (max-width: 800px){

          .home{
            min-height: 600px;
          }

          .home h1{
            font-size: 48px;
          }

          .home h3{
            font-size: 18px;
          }

          .home a.btn{
            padding: 15px 40px;
          }

        }

        @media (max-width: 600px){

          .home h3 {
            margin-top: 50px;
          }

        }

        /*-------------
          Footer
        -------------*/

        footer{
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
          color: #fff;
          background-color: #5989BD;
          padding: 60px 0;
        }

        footer ul{
          display: flex;
          margin-bottom: 25px;
          font-size: 32px;
        }

        footer ul li{
          margin: 0 8px;	
        }

        footer ul li:first-child{
          margin-left: 0;	
        }

        footer ul li:last-child{
          margin-right: 0;	
        }

        footer p{
          font-size: 14px;
          color: #FFF;
          margin-bottom: 10px;
        }

        footer p a{
          color: #fff;
        }

        @media (max-width: 700px){

          footer{
            padding: 80px 15px;
          }

        }
        `}</style>
    </>
  )
}
